nuxt-community/nuxt-i18n

lib/routes.js
Hi paulgv, 
This lib is so great, it saves me a lot of time to add i18n feature into my project.
I found a bug which causes Nested Routes children return empty, then I do some fix in this PR.
=> Fix nested routes children empty problem

lib/routes.js
Hi paulgv,
Sorry, I haven’t done enough test for the previous PR. 
The new PR have fixed the Nested Routes problem completely.
=> Fix nested routes children wrong path problem

lib/templates/i18n.routing.plugin.js
=> Fix for URLs with hashes. 

package.json
For changes see the [vue-i18n changelog](https://github.com/kazupon/vue-i18n/blob/dev/CHANGELOG.md)
=> Update vue-i18n version

docs/lazy-load-translations.md, src/templates/utils.js
Based on this feature request that I opened myself: 
https://github.com/nuxt-community/nuxt-i18n/issues/60
=> feat(loadLanguageAsync): Support promises return in lang files

docs/routing.md
Please feel free to enhance my english if you feel you need to.
I made this change because I've been struggling to get the pages working  ;)
=> Adding details about how pages property works

package.json, types/index.d.ts
=> nuxt-i18n types (refering #132)

package.json, yarn.lock
I included the issue number in the commit message. Not sure if it was a good idea… Sorry about that.
=> fix: Fix acorn-walk dependency (#137)

src/helpers/routes.js
I also ran into a problem when refreshing page with non-latin languages in url. A small fix for this problem.
=> Fixes #7: encodeURI for custom locale path

package.json, types/index.d.ts, types/test/index.ts, types/test/tsconfig.json, types/vue.d.ts, yarn.lock
=> Change Architecture/CodeStyle of TypeScript types + Test types

src/templates/middleware.js
For reference please see https://github.com/nuxt-community/nuxt-i18n/pull/148
=> Fixed minor issues in the browser detection

docs/vue-i18n-loader.md
I was trying to figure out how to use YAML in my <i18n> blocks, and noticed that there was no guide to do it. 
If there's some better way, please do let me know, since I want to use this myself :)
=> Docs for YAML in i18n blocks

src/helpers/utils.js, src/plugins/main.js, src/templates/middleware.js
This doesn't fix any specific bug but I've noticed that code doesn't
wait for sync dispatch actions which are async so I thought that fixing
that is the right thing to do.
=> improvement: wait for sync store to finish

package.json, src/helpers/components.js
Hi,
please merge this pr.
It will fix this issues: 
#301 
#134 
maoberlehner/vue-lazy-hydration#14
Cheers
Stephan
=> fix(acorn): implemented acorn-dynamic-import

package.json, src/plugins/routing.js, yarn.lock
Use module that detects protocol used in more accurate way.
=> fix: better server side protocol detection (fixes #123)

docs/routing.md
=> Fix number of strategies in Routing document

src/plugins/main.js, src/templates/middleware.js, test/__snapshots__/module.test.js.snap, test/fixture/basic/lang/en-US.js, test/fixture/basic/pages/fallback.vue, test/fixture/basic/pages/index.vue, test/module.test.js
Changes in middleware.js are just indentation fixes.
=> fix: missing redirect to domain with differentDomains enabled

docs/routing.md
This pull request adds an example of how to configure a custom path for a dynamic route using in-component options.
=> docs: add dynamic custom route example

package.json, yarn.lock
I hope this doesn't break anything.
=> Bump js-cookie version to 2.2.1

docs/es/options-reference.md, docs/options-reference.md, src/helpers/constants.js, src/plugins/main.js, types/nuxt-i18n.d.ts
=> feat: Added option to exclude subdomain from cookie domain

docs/seo.md, src/templates/seo-head.js, test/fixture/base.config.js, test/module.test.js, types/nuxt-i18n.d.ts
Resolves https://github.com/nuxt-community/nuxt-i18n/issues/522
=> feat: additional catchall hreflang tags

src/plugins/main.js, test/browser.test.js, test/fixture/basic/plugins/i18n-hooks.js
=> fix: sync store locale before triggering onLanguageSwitched listener

docs/es/basic-usage.md
It does not need the translation of the folder
=> Directory name is 'pages'

package.json, yarn.lock
Main advantage being that:
a) Release can be inspected and confirmed manually before committing.
b) Creates github releases automatically.
=> chore(release): use release-it package for automatic releases

docs/browser-language-detection.md
Added description where the language code comes from.
=> docs: Update branch-language-detection

docs/api/README.md, docs/es/api/README.md, docs/es/options-reference.md, docs/options-reference.md, src/helpers/constants.js, src/plugins/main.js, src/templates/utils.js, types/nuxt-i18n.d.ts
Remove forwardedHost for simplify. Ignore port when matching locale domain (it's a solution for working SSR: https://github.com/nuxt-community/nuxt-i18n/pull/627#discussion_r391029596).
=> Remove forwardedHost parameter

docs/options-reference.md, src/templates/middleware.js, types/nuxt-i18n.d.ts
Hi,
This PR address the feature request from #245.
Hope it suits !
Regards
=> feat: allow customization of rootRedirect status code

src/plugins/routing.js
=> fix: don't try to use route params when vuex.syncRouteParams

src/templates/plugin.main.js, test/browser.test.js
Also fixed an issue where would not respect query params when redirecting.
Resolves #702
=> fix: NavigationDuplicated error on loading 404 page in SPA

docs/api/README.md, docs/basic-usage.md, src/templates/plugin.routing.js, test/browser.test.js, test/fixture/basic/middleware/i18n-middleware.js, test/fixture/basic/pages/middleware.vue, test/module.test.js, types/test/index.ts, types/vue.d.ts
=> feat: add localeRoute API for getting the localized route

src/templates/plugin.main.js, test/module.test.js
=> fix: incorrect SEO links when vue-loader forces local i18n instance

src/templates/plugin.routing.js, src/templates/utils-common.js, test/fixture/no-lang-switcher/pages/about.vue, test/fixture/no-lang-switcher/pages/index.vue, test/module.test.js
=> Don't crash during generate with differentDomains enabled
