nuxt-community/nuxt-i18n

- lib/routes.js
Update to use chunkName such that nested routes can be translated.
Example:
pages
- parent.vue
- parent
- index.vue
- child.vue
In nuxt the parent route has no name and can not be translated in the current way.
> Use chunkName for translating

- lib/templates/i18n.routing.plugin.js
Fix #24 . Vue Mixin through plugins are already too far in the lifecycle to be registered on Nuxt's app. The app is in fact, already created when the plugins are registered. 
This PR extracts `localePath` and `getRouteBaseName` into factories so as to configure where to get `$router, $route, $i18n` and registers these 2 methods both in the mixin and on app.
( I don't believe anyone will use `switchLocalePath` from app... )
> Add localePath and getRouteBaseName to Nuxt's app

- lib/templates/i18n.routing.middleware.js
When no Accept-Language header is provided, a 500 server error is currently thrown. This should be avoided
Related: https://github.com/nuxt/nuxt.js/issues/2034#issuecomment-342602183
> Avoid server error without accept-language header

- lib/module.js
Plugin fails for latest `nuxt-edge` release, since vendor is deprecated.
This will allow both `nuxt` and `nuxt-edge` to build.
[You can read more here](https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67#a688)
> support for deprecated vendor in nuxt-edge build

- lib/templates/i18n.routing.plugin.js
If you have nested routes such as `services-development-de` (german) and  `services-development-en` (english) `services-development-de` becomes `servicesvelopment-de`.
This commit fixes that problem!
> Fix problem for route names containing locale code

- src/helpers/routes.js
This should resolve nuxt-community/nuxt-i18n#98
Sets route name *before* checking for children, and if children exist, delete the name property from the route.
cc @htchtc052
> Routes with children cannot have a name property.

- src/plugins/routing.js
Currently when an app supports multiple locales, which might match each others regex, the `getRouteBaseName` method returns the wrong result.
Example:
```
// locales = ['en', 'en-us']
// route.name = 'index___en-us'
// route.name.replace(regexp, '') will return 'index-us' and not 'index'
````
> fix: support locales with names that match other locales (`en` and `en-us`)

- src/plugins/seo.js
According to https://support.google.com/webmasters/answer/189077?hl=en href param should contain fully-qualified URL for the version of this page for the specified language/region:
> Alternate URLs must be fully-qualified, including the transport method (http/https), so:
https://example.com/foo, not //example.com/foo or /foo
This also requires baseUrl parameter in the module config. E.g.:
`modules: [
['nuxt-i18n', {
locales:               [
{code: 'en', iso: 'en-US', file: 'en.js'},
{code: 'fr', iso: 'fr-FR', file: 'fr.js'}
],
defaultLocale:         'en',
baseUrl:               'http://yoursite.com',
strategy:              'prefix',
detectBrowserLanguage: false,
vuex:                  {
moduleName: 'i18n',
mutations: {
setLocale: 'SET_LANG',
setMessages: false
}
},
vueI18n: …
> fix: making hreflang href full-qualified

- docs/options-reference.md
- docs/routing.md
- src/helpers/constants.js
- src/helpers/routes.js
This strategy generates the following routing.
nuxt.config.js:
```javascript
{
strategy: 'prefix_and_default',
locales: [
{
code: 'ja',
iso: 'ja',
name: '日本語',
},
{
code: 'en',
iso: 'en-US',
name: 'English',
},
],
defaultLocale: 'en',
}
```
routing:
```javascript
[
{
path: "/",
component: _3237362a,
name: "index___en"
},
{
path: "/en",
component: _3237362a,
name: "index___en"
},
{
path: "/ja",
component: _3237362a,
name: "index___ja"
},
]
```
demo: https://relaxed-snyder-764840.netlify.com/
> feat(strategy): add PREFIX_AND_DEFAULT strategy

- src/plugins/main.js
- src/templates/middleware.js
`i18n.locale` is reactive property. rerendered if it changed by using the `switchLocalePath` etc.
I think should that wait completed `fetch` or  `asyncData` methods.
I modified the changes timing of locale property
> feat: i18n.locale property changes when route changed

- package.json
I just updated to last version (5.4.0) and seen the `types` folder wasn't here in `node_modules`.
This PR is kind of a fix of my last merged PR about adding a TypeScript declaration file (#133).
I never published a NPM package so I was missing things around the package.json to make the types available in the bundle published.
> fix: Include Types in NPM bundle (when published)

- docs/browser-language-detection.md
- docs/options-reference.md
- src/helpers/constants.js
- src/templates/middleware.js
Reworked the browser detection, so that the cookie stores the language. This cookie value is now the preferred value when selecting the browsers locale.
Added the option to redirect every time the user visits the app
Added the options for a fallback locale if no language configured matches the browsers locale
Fixed a bug which lead to redirect loops when redirecting without a cookie
There is currently the issue of how to allow for language switches by the users choice. Accidentally this works when switching language via switchLocalePath because the redirect is not applied (as it is the same). If you have an idea how to "know" in the middleware that the user changed the language explicitly, please let me know (or if you have any other solutions).
Unfortunately I was not able to run the …
> Reworked the browser detection

- docs/seo.md
- src/plugins/main.js
- src/plugins/seo.js
- src/templates/seo-head.js
- src/utils/seo.js
- test/fixtures/basic/__snapshots__/module.test.js.snap
This PR exposes the SEO head hook function as `this.$nuxtI18nSeo` on components.
This allows to disable seo head mixin on all components (by setting `seo: false` in nuxt i18n options).
Then it's possible to do this in your app layout (or wherever):
```js
head () {
return this.$nuxtI18nSeo()
},
```
This greatly improves performance as SEO links are not recomputed for every components but only for the layout itself.
This changes is not breaking as the default global registration with the same behaviour remains if `seo: true` in the configuration.
Resolves: #144
> Expose the head SEO function to be used in layouts

- docs/options-reference.md
- src/helpers/constants.js
- src/plugins/main.js
This PR fixes https://github.com/nuxt-community/nuxt-i18n/pull/173
The problem occurs when deploying with SSR to a static host, such as AWS S3, then access `https://example.com/en`. Since there is no matching file,  Nuxt loads the fallback file `https://example.com/200.html`.
Now due to there is no server rendered state value defined(https://nuxtjs.org/guide/vuex-store#modules-mode), client preserves the state without the i18n module state, which raised an exception later when trying to set the locale.
The fix is to set `{ preserveState: false }` by default. If need to pass value from the server, then set`preserveState` to true in the options, and create a module vuex file as described here: https://nuxtjs.org/guide/vuex-store#modules-mode
> Fix state not defined issue in #173

- src/templates/middleware.js
**Case:** user enters the website on root path ( '/' ) with some query params. a common case of this is tracking query params.
**Current Behavior:** query params are lost when redirected to rootRedirect
**Desired Behavior:** user will redirect to the rootRedirect URL with the query params he had
This fixes the problem and preserves the query.
> rootRedirect's redirect does not preserve query

- src/templates/utils.js
According to the docs, lazy loaded locales should be able to return a promise. Doing this creates a warning message ever since nuxt switched to https://github.com/Rich-Harris/devalue .
This pull request prevents this warning. If lazy loading returns a promise, it waits for it before returning from `loadLanguageAsync` and returns the resolved value instead.
Resolves https://github.com/nuxt/nuxt.js/issues/4424 . Related: #161 .
> Wait for lazy loading promises

- README.md
Link was pointing to non-existing page. Added query parameter to make it point to questions.
If it should point to all kinds of issues then perhaps even https://cmty.app/nuxt/nuxt-i18n/ would be even better as link location.
> Fixed link to CMTY.

- src/plugins/routing.js
Old version didn't create correct object for the `router.resolve` by Vue. 
Params should start with a 0 according to the Vue specs. Solved this issue by copying the route object and changing the params. Resulting in not creating warnings for each file and component being checked by Webpack. 
Solution:
Create a copy of the route by substracting the params element. Params element has a pathMatch value. If not this will result in undefined and Vue will handle this the correct way. Otherwise baseRoute will result in a valid url and won't start a warning. Other checks will remain the same.
> Creates correct baseroute for switchlocalepath

- docs/seo.md
- src/index.js
- src/templates/seo-head.js
When using `prefix_and_default` strategy, the default language pages have "duplicated routes". For example, if I have a route `A/B` with `en` as default language, I will get `/en/A/B` and `/A/B` routes.
For SEO, we needs, then, a `rel="canonical"` link.
This MR add on the `/en/A/B` route a canonical link to the `/A/B` route
More info: https://support.google.com/webmasters/answer/182192#dup-content
PS: I tried to add tests, but I've failed to setup tests on multiple nuxt.config.js files :/
> Add canonical link to PREFIX_AND_DEFAULT duplicated pages

- docs/options-reference.md
- docs/routing.md
- src/helpers/constants.js
- src/helpers/routes.js
When a custom path has regular expression inside, encodeURI will escape special characters. `/foo/:slug-:id(\\d+)` will becomes `/foo/:slug-:id(%5Cd+)`.
This PR adds `encodeURI` option per the suggestion in #191. If it's set to false, then custom paths will not be encoded through `encodeURI` method. Since no encoding will happen, the user will need to ensure the correctly encoded paths are specified.
> Fixes #191: Add encodeURI option to allow skipping encodeURI for custom paths

- src/templates/middleware.js
Fixes vues store unsync state when lazy i18n loading and you try to change language
> Fixes #221 store unsync when changing language in lazy 

- docs/options-reference.md
- src/helpers/constants.js
- src/helpers/routes.js
- src/helpers/utils.js
- src/plugins/main.js
- src/plugins/routing.js
- src/templates/middleware.js
Fixed by adding a `___default` suffix (customizable) to prefix-less (default locale),
extra routes generated when using `prefix_and_default` strategy. So for example,
with 'en' being default locale, two generated index 'en' routes will have names:
- index___en
- index___en___default
Additional changes done to handle extra suffix properly, without breaking existing
behavior. That is, when being on a route without prefix, `localePath` and
`switchLocalePath` will still return paths without prefix.
Sort of unrelated to this change but made `routesNameSeparator` not be exposed
on `app.i18n` as it's neither documented to be exposed there nor it shouldn't be
needed for anything.
> Fix duplicated route names with prefix_and_default strategy (fixes #140)

- src/templates/seo-head.js
On visiting route that is not defined (404), and module's `defaultLocale`
is not defined (default), the code in main.js would set `app.i18n.locale`
to null and when the seo code would run, it would crash on trying to
access property `iso` of it. So don't allow seo code to run when locale
is not defined.
> Fix 'cannot read property "iso"' crash (issue #80)

- docs/lang-switcher.md
- src/index.js
- src/plugins/main.js
- src/plugins/routing.js
- src/templates/middleware.js
- types/vue.d.ts
Make sure that after first visit, when we detect browser language and
store locale cookie, we reuse that cookie and re-set language during
navigation. Before this change, even with `alwaysRedirect` enabled, we
have only redirected on first visit and on next visits user got default
language again.
Changes:
- Don't base ability to set client-side cookies on the `isSpa` flag.
That flag signified whether app was in 'spa' mode (another possible
mode is 'universal') and it only allowed setting client-side cookies
in that mode. That's wrong as it should also be possible to set
client-side cookies when running on client side in 'universal' mode.
Use `process.client` and `process.server` instead, which are more
appropriate flags to check for that purpose.
- Expose setLocaleCookie on `app.i18n` …
> feat: Always redirect to language that was saved in cookie

- docs/basic-usage.md
- docs/setup.md
- src/index.js
- test/fixtures/basic/nuxt.config.js
Hi,
A little feature to allow to configure this module via global options just like other official modules (e.g. [axios](https://axios.nuxtjs.org/setup), [auth](https://auth.nuxtjs.org/getting-started/setup) etc ...).
I hope it will be merged soon :smiley: 
Regards
> Global options configuration

- docs/lazy-load-translations.md
- src/plugins/main.js
Fallback locale is needed to properly handle strings that exist in
base/fallback locale but not in currently used one.
Fix from @orblazer
> Load fallback locale when needed if lazy-loading (fixes #34)

- src/plugins/main.js
Even though `req` doesn't seem used in the file, it is added after
templates are filled in.
> Fix exception when using multiple domains option (fixes #293)

- package.json
- src/index.js
Also only require makeRoutes when actually building app.
fixes #297.
> fix: add missing vue-template-compiler dependency (fixes #297)

- package.json
- src/helpers/components.js
- src/index.js
We can't have explicit dependency as that package requires its and vue's
versions to match exactly and we can't ensure that. Remove it and just
make sure that this dependency is only used on building nuxt app (done
before already, just added more explanation in comments).
> fix: remove explicit dependency on vue-template-compiler (fixes #297)

- package.json
- src/plugins/main.js
- src/templates/middleware.js
- yarn.lock
This PR aims at fixing the current behavior of `nuxt-i18n` when setting the detected language cookie.
If someone were to set a cookie within a Nuxt server-middleware (e.g. a CSRF token cookie), it will be discarded only the first time `nuxt-i18n` is setting the language redirection cookie.
The root cause comes from using `res.setHeader('Set-Cookie', redirectCookie)`: it no longer implicitly append the cookie value to the current list of `Set-Cookie` values in Express > 4, as explained here: https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x#ressetheaderset-cookie-val
To keep compatibility of this middleware with requests/responses from Express/Connect/etc., using the `cookies` package instead of `cookie` seems like a sensible choice to me, and fixes nicely the issue.
If I …
> fix: do not discard already present set-cookie header

- package.json
- src/plugins/main.js
- src/templates/middleware.js
- yarn.lock
PR #327 introduced a significant increase of vendors bundle size, as reported in issue #330.
The root cause was the replacement of the `cookie` package with the `cookies` one, while fixing a severe bug in `Set-Cookie` headers handling for the SSR language redirection cookie.
This PR reverts to using the `cookie` package but performs manually the `Set-Cookie` header handling, exactly the way the `cookies` package does (i.e. no previous cookie, a single cookie or a list of cookies).
Hopefully, this one will do the trick!
> fix: revert using cookies package to fix cookie headers handling

- src/plugins/routing.js
Makes that dependency be tree-shaken and not included at all on the
client. As a side effect, fixes IE11 that had problem with JS default
arguments used in is-https package.
> Only require is-https dependency on the server

- types/vue.d.ts
This follows up on the discussion here: https://github.com/nuxt-community/nuxt-i18n/pull/319#discussion_r289303554
> rchl 22 days ago  Member
> I don't really know much about typescript or writing declaration files but should this interface be defined outside of the declare module block?
> 
> kevinmarrec 20 days ago  Member
> @rchl Is right, the interface definition should be before declaring module and not inside.
> fix: Move SEO types out of Vue module declaration

- docs/options-reference.md
- docs/seo.md
- src/helpers/constants.js
- types/vue.d.ts
As that option causes issues (performance and sometimes even breaking
some UI frameworks), disable it by default. There is alternative
solution described in documentation that doesn't have those issues.
Resolves #346
> (for next major version!) Disable seo by default (fixes #346)

- CHANGELOG.md
- docs/lang-switcher.md
- docs/options-reference.md
- package.json
- src/helpers/constants.js
- src/plugins/main.js
- src/plugins/routing.js
- src/templates/utils.js
- test/fixtures/basic/__snapshots__/module.test.js.snap
- test/fixtures/basic/module.test.js
- test/fixtures/basic/pages/posts.vue
- test/fixtures/basic/pages/posts/_slug.vue
- test/fixtures/basic/pages/posts/index.vue
Adds support for translating dynamic route parameters via the Vuex store module
BREAKING CHANGE: `preserveState` is now set automatically when registering the store module and
cannot be set via the configuration anymore
When using `switchLocalePath` to create a global lang switcher component, there's currently no way for the method to know how to translate dynamic parameters. This is an attempt to address this issue.
This has been published as a prerelease on NPM, to test this version, install `v6.0.0-0` with Yarn:
```sh
yarn add nuxt-i18n@6.0.0-0
```
Or NPM:
```sh
npm i nuxt-i18n@6.0.0-0
```
Refer to the new documentation section to see how to use this in your app: [Dynamic route parameters](https://github.com/nuxt-community/nuxt-i18n/blob/9f92005da111c4536191f4749db4fc289cd1ae2e/docs/lan …
> feat: Dynamic route parameters translation

- docs/options-reference.md
- src/helpers/constants.js
- src/plugins/main.js
BREAKING CHANGE: The mutations responsible for syncing nuxt-i18n's store module with vue-i18n's
locale and messages are now disabled by default, you'll need to manually re-enable them in the
module's configuration
> refactor: Disable setLocale & setMessages mutations by default

- src/plugins/routing.js
- test/fixtures/basic/module.test.js
When using Nuxt's router in [hash mode](https://nuxtjs.org/api/configuration-router#mode) `localePath` returns a string containing a hash which breaks the router functionality.
https://codesandbox.io/s/nuxt-i18n-localepath-hash-mode-5xfz4
Both the _About_ button on the [homepage](https://5xfz4.sse.codesandbox.io/#/) and the _Back home_ button on the [about page](https://5xfz4.sse.codesandbox.io/#/about) do not resolve.
Vue-Router seems to work when you provide a string of a route without a hash in front.
Make `localePath` return the resolved routes `route.fullPath` instead of the `href`. `route.fullPath` does not include the starting hash character.
I added a few extra tests to specifically test for these conditions. Because `jsdom`, used by Nuxt's `renderAndGetWindow` does not allow …
> (fix): localePath in hashmode

- docs/routing.md
- src/helpers/routes.js
- src/helpers/utils.js
Hello,
Here is a PR to use default locale's custom path when a custom path is not defined for a locale.
It can help if you have a lot of locales to manage and only want a custom path for a few of them.
> Use default locale's custom path if not defined for a locale

- docs/options-reference.md
I think that documents should show clearly what kind of value to use for `iso` of options.
So, I've add description of iso code to documents as comment of source code.
> Add description of iso code to documents

- docs/options-reference.md
- src/helpers/constants.js
- src/helpers/utils.js
- src/plugins/main.js
- `vuex.mutations.setLocale` has been renamed to `vuex.syncLocale`
- `vuex.mutations.setMessages` has been renamed to `vuex.syncMessages`
BREAKING CHANGE: Store module's options have been flattened and renamed
> refactor: Rename and flatten vuex options

- README.md
- docs/setup.md
Removing link to CMTY as nobody replies there (I just did a bit but I don't think I'll able to keep monitoring it).
> docs: Add link to discord and add info about types configuration

- package.json
- src/plugins/main.js
- types/index.d.ts
- types/nuxt-i18n.d.ts
- types/vue.d.ts
Changes:
- exported `NuxtVueI18n` namespace to allow to annotate configuration
object in `nuxt.config.ts`.
- fixed various types in Options, made all optional to make them
actually usable, added missing ones.
- moved getLocaleCookie, setLocaleCookie and SetLocale to proper
interface.
- removed `return null` from `getLocaleCookie` to simplify types.
- Updated NuxtI18nSeo interface to use VueMeta types.
- Also removed `app.$t` API as it never worked - it needs to be called
on the VueI18n instance instead.
> fix(types): various fixes to type definitions

- docs/.vuepress/config.js
- docs/api/README.md
- docs/routing.md
Note that current `vuepress` version fails to run when there is also `nuxt` in dependencies so `yarn remove nuxt` for testing.
Resolves #282
> docs: add documentation page with API reference

- .gitignore
- src/plugins/main.js
- src/templates/middleware.js
- test/browser.test.js
When generating static files with `nuxt generate` (with default `universal` mode), initial load of the URL doesn't trigger middleware.
Nuxt triggers middleware in those cases for initial load:
- universal (server: yes, client: no)
- spa (server: --, client: yes)
- universal+generate (server: --, client: no)
- spa+generate (server: --, client: yes)
Due to middleware not triggering on initial load, browser language wasn't detected and cookie was not set, which later caused failure to update locale on navigating to route from other locale. That's because detection happened on second navigation and overridden target route's locale.
To fix, trigger language detection from the plugin first.
For some cases that means that middleware will attempt to trigger detection again but it will be …
> fix: failure to change locale on initial try with nuxt generate

- package.json
- src/helpers/components.js
- src/helpers/routes.js
- src/helpers/utils.js
- src/index.js
- src/plugins/main.js
- src/plugins/routing.js
- src/plugins/seo.js
- src/templates/middleware.js
- src/templates/options.js
- src/templates/seo-head.js
- src/templates/utils.js
Since using lodash templates makes it impossible to properly lint files,
create options.js file that has all options stringified and exported so
that all other files can just import those without using templates.
That makes it possible to lint files and also see exactly which
variables are used and which are missing which was really hard when
whole functions were inlined when processing templates.
Instead of passing various functions through templates and stringifying
them, keep them in templates/utils.js and import directly. This also
has benefit of avoiding code duplication in processed files.
Compute localeCodes and some other variables up-front as when those are
based on user settings, they are guaranteed not to change so we don't
have to processes them on each request/route change. …
> refactor: avoid using templates

- .circleci/config.yml
- src/index.js
- test/module.test.js
When there are no `locales` defined, `buildLocalizedRoutes` goes through
all routes, finds no routes matching `locales` and so returns empty
list of routes that then replaces original routes.
Skip that altogether when no locales are defined so that original routes
are left alone.
Resolves #444
> fix: all routes removed when locales are absent

- src/plugins/routing.js
- test/module.test.js
The case that was wrong was when calling `localePath` with
`{ path: '/about' }` argument when strategy was NO_PREFIX. Code
has prefixed result with a locale while it never should.
Case when passing component name to `localePath` was not affected
by the bug.
> fix: NO_PREFIX - localePath with `path` returns route with prefix

- src/helpers/routes.js
- test/fixture/basic/pages/posts/index.vue
- test/module.test.js
PR includes two separate (but in the same family) bugs, in two separate commits.
Refer to individual commits messages for more info.
Resolves #356, #359
> fix: Route name missing for routes with children + Locale prefixes missing for child routes with custom paths

- README.md
That's because for some users it's concerning to read the note - they
think the module is not maintained while currently at least it is. :)
> chore(docs): Remove note about need for maintainers

- src/plugins/routing.js
- test/__snapshots__/module.test.js.snap
- test/browser.test.js
- test/fixture/basic/middleware/i18n-middleware.js
- test/fixture/basic/pages/middleware.vue
- test/module.test.js
- yarn.lock
switchLocalePath didn't work from a Nuxt plugin or middleware
(from context.app) as it accessed properties on `this` that were not
accessible from there.
Fixed by creating a proxy interface that is consistent for both
Vue instances and Nuxt context so that switchLocalePath can access
same properties from it and get expected results.
Also:
- Updated `differentDomains` tests to not use snapshot testing.
Those actually were wrongly tested due to bug in test utils but
the failure wasn't caught in snapshot (it was supposed to have
SEO disabled).
Resolves #480
> fix: make switchLocalePath work from Nuxt plugin or middleware

- src/plugins/main.js
- src/templates/middleware.js
I didn't realize that fact when creating __route property, but the
context object stays the same during lifetime of the application and
the `route` property is updated to match current route so we can use
that instead of creating extra from middleware.
> refactor: avoid storing route in a property

- src/plugins/main.js
Avoids warnings triggered by browsers related to cookie not having
sameSite attribute.
More details at https://web.dev/samesite-cookies-explained/
Resolves #516
> fix: set sameSite=Lax option for detected-language cookie

- src/plugins/main.js
- src/templates/utils.js
- test/browser.test.js
This fixes bug that triggers in quite specific situation - SPA mode
with Vue-router set to use hash mode.
In that setup if user navigates directly to an URL that will trigger
certain route and that route's `path` does not *exactly* match the
path user navigated to (for example due to extra trailing slash
or query parameter in user's URL), that triggers redirect that fails
due to target route being the same. That leaves current route in a
broken state. I assume because that route wasn't committed yet.
Fix by comparing routes in more sophisticated way than just comparing
route's path. Instead use VueRouter to resolve route from path and then
compare that with current route.
Resolves #490
> fix: Direct navigation to URL in SPA with vue-router in hash mode

- src/helpers/routes.js
- test/fixture/dynamic/nuxt.config.js
- test/fixture/dynamic/pages/_.vue
- test/module.test.js
With there being a catch-all route (_.vue) in pages directory,
depending on the order of locales in configuration, default locale's
route could shadow locale-specific one due to being first on the list
of generated routes. For example, routes were generated like so:
```
routes: [{
path: "/*",
component: _0bdbeb02,
name: "all___en"
}, {
path: "/fr/*",
component: _0bdbeb02,
name: "all___fr"
}],
```
which meant that `/*` route never allowed later ones to be matched.
Fix by sorting routes by specificity, using function exposed
by `@nuxt/utils` (only from 2.10.2).
Resolves #152
> fix: default locale catch-all route overrides locale-specific one

- src/index.js
- src/templates/middleware.js
resolves #531 
there are not functional/breaking changes. Generally adding middleware by module is tricky and I didn't see good practices how we should do it, but we can make sure we don't conflict with other modules.
> refactor: change middleware key to avoid conflicts with other modules

- .circleci/config.yml
Trying to fix "Segmentation fault (core dumped)" error.
> Use Node 12.1.0 for testing instead of latest

- docs/api/README.md
- src/plugins/routing.js
- test/module.test.js
- types/vue.d.ts
In 8a1c052f340ad8f86d62fb1e3c6f1107360fb0e9 the functionality to pass
route to `getRouteBaseName` was accidentally removed. Bring that back
and update documentation to state what's the actual argument. It was
incorrectly specifying `string | Location` as argument while
currently it has to be a `Route`.
Resolves #539
> fix(routing): Restore handling of route argument in getRouteBaseName

- docs/basic-usage.md
- src/plugins/routing.js
- test/module.test.js
support passing in path as string to localePath()
`localePath('/app/profile')`
[Stackoverflow Conversation](https://stackoverflow.com/questions/58968237/nuxtjs-i18n-vue-router-route-with-name-about-us-en-does-not-exist/59497900#59497900)
> feat: support paths in localePath()

- docs/options-reference.md
- package.json
- src/plugins/main.js
- src/templates/options.js
- test/fixture/basic/plugins/vue-i18n.js
- test/module.test.js
- types/nuxt-i18n.d.ts
- yarn.lock
Added support for specifying path to local file for options passed to
vue-i18n (the `vueI18n` key of `nuxt-i18n` configuration). This allows
for configuration some options that have function type which previously
would fail due to stringifying and lack of possibility to import stuff.
Resolves #585, resolves #237
> feat: support external configuration file for vue-i18n options

- docs/es/vue-i18n-loader.md
- docs/vue-i18n-loader.md
- package.json
- src/index.js
- test/fixture/basic/pages/loader-yaml.vue
- test/module.test.js
- yarn.lock
Hello. Thank you for awesome package :)
The vue-i18n-loader package name & repo has been changed. Please see the following.
> https://github.com/intlify/vue-i18n-loader/pull/69/.
This PR update following.
* dependency
* docs
* loader in `index.js`
> chore(deps): migrate vue-i18n-loader package name

- src/plugins/main.js
- test/module.test.js
When `defaultLocale` was not set, and there was locale with `en-US` code,
the code has failed to initialize locale (including failure to lazy-load lang
files) due to `newLocale === app.i18n.locale` check that returned true even
though we haven't fully initialized yet.
Resolves #628
> fix: Incomplete initialization with 'en-US' locale code and no default

- types/nuxt-i18n.d.ts
Add `vueI18nLoader` to `AllOptionsInterface` of types.
Because Options has `vueI18nLoader`.
https://nuxt-community.github.io/nuxt-i18n/options-reference.html
> Add vueI18nLoader to AllOptionsInterface of types

- src/plugins/main.js
- test/browser.test.js
When:
- `detectBrowserLanguage` was enabled
- `detectBrowserLanguage.fallbackLocale` was not specified
- preferred browser language was set to one that nuxt-i18n configuration
didn't support
then navigating to another locale in SPA mode has updated the URL but
failed to change locale.
Fix by correcting the logic of browser language detection which was
supposed to return false when it didn't manage to detect language but
didn't always do that.
Resolves #643
> fix: locale not updated on navigation (no fallbackLocale)

- docs/browser-language-detection.md
- src/plugins/main.js
- src/templates/utils-common.js
- test/unit.test.js
For detecting and redirecting to browser language the module only
looked at first two letters of the language codes provided by the
browser so it wasn't able to match up more specific locale codes like
en-GB or zh-CN.
Fix by matching checking against full language code first and then
falling back to only first two letters if no higher-ranked code
was found.
Resolves #650
Resolves #563
> feature: match against full language code provided by the browser

- src/templates/utils-common.js
- test/unit.test.js
Related to PR #651 and new browser language detection logic that
takes into account full (like en-GB) language codes.
> fix: match full browser locale case-insensitively (same as short)

- src/plugins/main.js
If `vuex.syncLocale` is true, then any locale determined on the server during SSR should be used as initial value by the client.
This also allows:
- Not to determine the language twice when a page is loaded (once on the server, then again in the client)
- Other plugins (e.g. user session in a universal app) to alter the locale during bootstrap (`await app.i18n.setLocale('xx')`) and make sure that that locale is re-used on the client.
Note that I think that this should be default behavior for this module.
> fix: use the synced locale on client if set during SSR

- src/plugins/main.js
- test/module.test.js
The SEO code has crashed due to trying to get `iso` property for locale
that didn't exist. It's because we've allowed to set `$i18n.locale` to
an invalid value due to not validating the locale cookie in all cases.
This crash only triggered when certain conditions have aligned:
- using `no_prefix` strategy as then middleware can't get locale from route
- using `detectBrowserLanguage.alwaysRedirect` as then we try to redirect
even when cookie is already set
- using `seo = true` or manual SEO integration as the crash happened
in SEO code
Change `getLocaleCookie` to only return locale code if it's valid.
> fix: crash with invalid locale cookie + no_prefix strategy + SEO

- package.json
- yarn.lock
The relevant issue: https://github.com/kazupon/vue-i18n/issues/849
> fix: lock vue-i18n version to 8.16.0 until crashing issue is fixed

- package.json
- src/helpers/constants.js
- src/plugins/main.js
- src/templates/middleware.js
- types/nuxt-i18n.d.ts
- yarn.lock
More details in https://github.com/kazupon/vue-i18n/issues/849
> fix: crash with latest vue-i18n related to using null locale

- package.json
- src/index.js
- yarn.lock
The old vue-i18n-extensions was moved to organization and old package
won't receive updates.
> chore(deps): switch to @intlify/vue-i18n-extensions

- docs/es/routing.md
- docs/routing.md
As I spent some times to understand how to customize i18n urls for wildcard pages (`_.vue`), I suggest an example in the documentation to illustrate it.
> chore(docs): add example for wildcard route configuration

- docs/es/options-reference.md
- docs/es/routing.md
- docs/options-reference.md
- docs/routing.md
- package.json
- src/templates/middleware.js
- src/templates/plugin.main.js
- src/templates/plugin.routing.js
- src/templates/utils-common.js
- src/templates/utils.js
- test/browser.test.js
- test/fixture/basic/components/LangSwitcher.vue
- test/fixture/basic/pages/posts/_slug.vue
- test/fixture/basic/pages/posts/index.vue
- test/module.test.js
fix: redirect from 404 to defaultLocale if there is matching route
Changes the `setLocale` logic to, in case current route is 404, to
try to find a matching one for current locale. This is for situations
when using `prefix` strategy where the root (`/`) route doesn't exist.
We will try to find and redirect to prefixed route matching resolved locale.
Also worked around Nuxt issue (https://github.com/nuxt/nuxt.js/issues/4491 )
with `redirect` not working when called from a plugin in SPA mode.
Required for the above fix above to be functional in SPA.
Resolves #677
Resolves #491
> fix: redirect from 404 to defaultLocale if there is matching route

- src/index.js
- src/templates/plugin.main.js
- test/browser.test.js
With Nuxt generate & universal mode Nuxt doesn't trigger middleware
on initial loading so we need to do it manually so that possible
redirection is handled.
> fix: trigger language detection on initial load in generated mode

- .eslintrc.js
- src/helpers/routes.js
- src/index.js
- test/browser.test.js
To avoid having to create server-side redirect rules, the non-prefixed
routes are not removed when using prefix strategy with Nuxt generate.
The non-prefixed routes should automatically redirect to default locale
routes.
Resolves #700
> fix: don't leave out non-prefixed routes for generate + prefix strategy

- docs/basic-usage.md
- docs/es/basic-usage.md
- src/templates/plugin.routing.js
- test/fixture/basic/pages/posts/_slug.vue
- test/module.test.js
In that case current route is used as a fallback for determined the target.
Resolves #691
> feat: add support for using localePath with no route name and path

- docs/es/routing.md
- docs/options-reference.md
- docs/routing.md
- src/helpers/constants.js
- src/helpers/routes.js
- types/nuxt-i18n.d.ts
This could be considered a breaking change but since I only know of it
breaking things rather than helping anything and there are no tests that
would prove me otherwise, I think it's safe to remove without releasing
a major version.
Also, Nuxt doesn't encode paths either so this change aligns with it.
Resolves #712
> fix: remove "encodePaths" option and don't encode paths by default

- src/templates/plugin.routing.js
- test/module.test.js
When using "localePath" with a route path argument (rather than route name),
there was a bug with picking prefixed route path for default
route rather than preferred non-prefixed path.
Resolve #721
> fix: favor non-prefixed route with prefix_and_default strategy

- src/helpers/routes.js
- src/index.js
- src/templates/seo-head.js
- test/module.test.js
Module was adding a trailing slash for extra routes that
it was generating.
This isn't normally a problem as VueRouter runs by default in
non-strict mode and normalizes paths to not have trailing slashes but
when the "router.trailingSlash = false" option was set in Nuxt, then
the matching was strict and actually made trailing slashes appear in
the path.
Follow the same logic as Nuxt and:
- don't add trailing slashes by default or when "router.trailingSlash"
option is set to "false"
- add trailing slashes when "router.trailingSlash" option is set
to "true"
Resolves #717
> fix: don't add trailing slashes to generated routes

- package.json
- src/templates/plugin.main.js
- test/fixture/basic/pages/loader-yaml.vue
- test/module.test.js
- yarn.lock
When component specifies some VueI18n options using a plain i18n object
in component options, VueI18n creates a separate component-local instance
of itself. That instance wasn't extend with nuxt-i18n-specific properties
that root instance has.
Fix by adding an API in vue-i18n for handling that and use it here.
Resolves #557
> fix: crash on using nuxt-i18n properties in a component with i18n options

- src/index.js
Changing to using the "build:extendRoutes" hook wasn't necessary and
was a breaking changed for users who use extendRoutes() and expect
nuxt-i18n to process those routes.
Resolves #750
> fix: revert back to generating routes from extendRoutes()

- docs/es/lazy-load-translations.md
- docs/lazy-load-translations.md
- src/templates/utils.js
- test/fixture/basic/lang/fr-FR.js
- test/fixture/basic/pages/locale.vue
- test/module.test.js
When using the function export for lazy-loaded locales, the function
will now also receive locale code, apart from context.
Resolves #742
> feat: pass to-be-loaded locale when lazy-loading from exported function

- CHANGELOG.md
- package.json
- src/templates/middleware.js
- src/templates/plugin.main.js
- test/browser.test.js
- test/fixture/basic/pages/index.vue
- test/fixture/basic/pages/posts.vue
When we've detected browser language and need to redirect we need to do
it from the middleware for the page to transition correctly. The problem
is Nuxt doesn't trigger middleware for initial navigation in static
mode (the idea is that it already ran when generating page on the server),
so we can't do it properly.
Fixed by hooking into the VueRouter "beforeEach" navigation hook so that
we can handle it from the right place. Still, as Nuxt doesn't know that
we are redirecting, it would throw some errors trying to load previous
page. So use "location.assign()" to "hard" redirect.
Resolves #737
> fix: initial redirect breaks reactivity in static mode

- package.json
- src/index.js
- src/templates/plugin.routing.js
- test/browser.test.js
- test/fixture/base.config.js
- test/fixture/basic/pages/dynamicNested/index.vue
- test/module.test.js
- test/utils/http-server-internal.js
- test/utils/web-server.js
Respect "router.trailingSlash" option when using "localePath" with
an absolute path as an argument. The trailing slash is now normalized
according to that option (true: add trailing slash,
false or undefined: remove trailing slash). That excludes the root path
which always includes trailing slash.
An extra fix for #717
> fix: handling of trailing slash in localePath

- docs/api/README.md
- types/test/index.ts
- types/vue.d.ts
Event though the result is actually a route object, the point of
localeRoute is to return something that can be passed to VueRouter.push()
and that needs to be a Location object.
Location is basically a subset of Route plus some optional properties
so treating Route as Location should be fine.
Resolves #776
> Change return type of localeRouter from Route to Location

- types/nuxt-i18n.d.ts
Enables to set `detectBrowserLanguage` to be `false` in case of disabling redirection.
https://github.com/nuxt-community/nuxt-i18n/blob/master/docs/options-reference.md
> fix(types): fix type of detectBrowserLanguage to allow false
